strategy:
  class: CCIStrategy
  module: functions.strategies.cci_strategy
  results_dir: cci_strategy
name: CCI Threshold Strategy
parameters:
  cci_period:
  - 14
  - 20
  - 30
  threshold:
  - 100
  - 120
  - 150
  take_profit_pips:
  - 15
  - 20
  - 30
  - 40
  stop_loss_pips:
  - 10
  - 15
  - 20
  - 30
parameters_bayesian:
  cci_period:
  - 10
  - 40
  threshold:
  - 80
  - 180
  take_profit_pips:
  - 15
  - 50
  stop_loss_pips:
  - 10
  - 35
