strategy:
  class: CMFReversal
  module: functions.strategies.chaikin_money_flow_reversal
  results_dir: chaikin_money_flow_reversal
name: Chaikin Money Flow Reversal
parameters:
  cmf_period:
  - 14
  - 20
  - 30
  threshold:
  - 0.03
  - 0.05
  - 0.08
  ema_filter:
  - 30
  - 50
  - 100
  take_profit_pips:
  - 15
  - 25
  - 35
  - 50
  stop_loss_pips:
  - 12
  - 18
  - 24
  - 30
parameters_bayesian:
  cmf_period:
  - 10
  - 40
  threshold:
  - 0.02
  - 0.15
  ema_filter:
  - 20
  - 200
  take_profit_pips:
  - 10
  - 70
  stop_loss_pips:
  - 8
  - 40
