strategy:
  class: FractalBreakout
  module: functions.strategies.fractal_breakout
  results_dir: fractal_breakout
name: Fractal Breakout Strategy
parameters:
  lookback:
  - 20
  - 30
  - 40
  take_profit_pips:
  - 20
  - 30
  - 40
  - 60
  stop_loss_pips:
  - 15
  - 20
  - 25
  - 30
parameters_bayesian:
  lookback:
  - 15
  - 60
  take_profit_pips:
  - 15
  - 80
  stop_loss_pips:
  - 10
  - 40
