strategy:
  class: IchimokuKijunCross
  module: functions.strategies.ichimoku_kijun_cross
  results_dir: ichimoku_kijun_cross
name: Ichimoku Kijun Cross
parameters:
  tenkan_period:
  - 7
  - 9
  - 12
  kijun_period:
  - 22
  - 26
  - 34
  take_profit_pips:
  - 15
  - 20
  - 30
  - 40
  stop_loss_pips:
  - 10
  - 15
  - 20
  - 30
parameters_bayesian:
  tenkan_period:
  - 5
  - 15
  kijun_period:
  - 20
  - 40
  take_profit_pips:
  - 15
  - 50
  stop_loss_pips:
  - 10
  - 35
