strategy:
  class: KeltnerChannelBreakout
  module: functions.strategies.keltner_channel_breakout
  results_dir: keltner_channel_breakout
name: Keltner Channel Breakout
parameters:
  ema_period:
  - 20
  - 30
  atr_period:
  - 10
  - 14
  - 20
  multiplier:
  - 1.5
  - 2.0
  - 2.5
  take_profit_pips:
  - 15
  - 20
  - 30
  - 40
  stop_loss_pips:
  - 10
  - 15
  - 20
  - 30
parameters_bayesian:
  ema_period:
  - 15
  - 40
  atr_period:
  - 8
  - 25
  multiplier:
  - 10
  - 30
  take_profit_pips:
  - 15
  - 50
  stop_loss_pips:
  - 10
  - 35
