strategy:
  class: KeltnerSqueezeBreakout
  module: functions.strategies.keltner_squeeze_breakout
  results_dir: keltner_squeeze_breakout
name: Keltner Squeeze Breakout
# When using best_params below, interpret stop/take values with this scale (e.g., 0.11 -> 11 pips when scale=100)
pips_param_scale: 1
# Keys to scale by pips_param_scale
pips_param_keys:
  - stop_loss_pips
  - take_profit_pips
parameters:
  period:
  - 14
  - 20
  - 28
  bb_std:
  - 1.5
  - 2.0
  - 2.5
  kc_mult:
  - 1.2
  - 1.5
  - 2.0
  take_profit_pips:
  - 20
  - 30
  - 40
  - 60
  stop_loss_pips:
  - 15
  - 20
  - 25
  - 30
parameters_bayesian:
  period:
  - 8
  - 20
  bb_std:
  - 1.2
  - 1.8
  kc_mult:
  - 1.8
  - 3.2
  take_profit_pips:
  - 4.0
  - 20.0
  stop_loss_pips:
  - 2.0
  - 13.0
# Not sure if I can add comments here but let's see
parameters_bayesian_15m:
  period:
  - 10
  - 40
  bb_std:
  - 1.2
  - 3.0
  kc_mult:
  - 1.0
  - 2.5
  take_profit_pips:
  - 15
  - 80
  stop_loss_pips:
  - 10
  - 40
best_params_15m:
  period: 10
  bb_std: 1
  kc_mult: 2
  take_profit_pips: 15
  stop_loss_pips: 18
best_params_overfitted:
  period: 16
  bb_std: 1.243501
  kc_mult: 2.595969
  take_profit_pips: 10.78
  stop_loss_pips: 10.44
best_params_x:
    period: 17
    bb_std: 1.2476874670120126
    kc_mult: 3.18513049255417
    take_profit_pips: 11.221918150346148
    stop_loss_pips: 10.655016358358365
best_params_best:
    period: 17
    bb_std: 1.2115077579776679
    kc_mult: 3.1919640247506735
    take_profit_pips: 11.601119961759514
    stop_loss_pips: 11.123290781386578
best_params:
  period: 17
  bb_std: 1.2417472239683929
  kc_mult: 2.9961328901142
  take_profit_pips: 11.257479310639521
  stop_loss_pips: 11.9056041867743