strategy:
  class: KeltnerSqueezeBreakout
  module: functions.strategies.keltner_squeeze_breakout
  results_dir: keltner_squeeze_breakout
name: Keltner Squeeze Breakout
parameters:
  period:
  - 14
  - 20
  - 28
  bb_std:
  - 1.5
  - 2.0
  - 2.5
  kc_mult:
  - 1.2
  - 1.5
  - 2.0
  take_profit_pips:
  - 20
  - 30
  - 40
  - 60
  stop_loss_pips:
  - 15
  - 20
  - 25
  - 30
parameters_bayesian:
  period:
  - 1
  - 8
  bb_std:
  - 1.1
  - 1.4
  kc_mult:
  - 1.4
  - 2.2
  take_profit_pips:
  - 0.15
  - 4
  stop_loss_pips:
  - 0.10
  - 3
# Not sure if I can add comments here but let's see
parameters_bayesian_15m:
  period:
  - 10
  - 40
  bb_std:
  - 1.2
  - 3.0
  kc_mult:
  - 1.0
  - 2.5
  take_profit_pips:
  - 15
  - 80
  stop_loss_pips:
  - 10
  - 40
best_params_15m:
  period: 10
  bb_std: 1
  kc_mult: 2
  take_profit_pips: 15
  stop_loss_pips: 18
best_params:
  period: 6
  bb_std: 1.12051
  kc_mult: 1.71934
  take_profit_pips: 3.88128
  stop_loss_pips: 0.10793