strategy:
  class: KeltnerSqueezeBreakout
  module: functions.strategies.keltner_squeeze_breakout
  results_dir: keltner_squeeze_breakout
name: Keltner Squeeze Breakout
parameters:
  period:
  - 14
  - 20
  - 28
  bb_std:
  - 1.5
  - 2.0
  - 2.5
  kc_mult:
  - 1.2
  - 1.5
  - 2.0
  take_profit_pips:
  - 20
  - 30
  - 40
  - 60
  stop_loss_pips:
  - 15
  - 20
  - 25
  - 30
parameters_bayesian:
  period:
  - 10
  - 40
  bb_std:
  - 1.2
  - 3.0
  kc_mult:
  - 1.0
  - 2.5
  take_profit_pips:
  - 15
  - 80
  stop_loss_pips:
  - 10
  - 40
best_params:
  period: 10
  bb_std: 1
  kc_mult: 2
  take_profit_pips: 15
  stop_loss_pips: 18