strategy:
  class: MACDMomentum
  module: functions.strategies.macd_momentum
  results_dir: macd_momentum
name: MACD Momentum Strategy
parameters:
  macd_fast:
  - 8
  - 12
  - 16
  macd_slow:
  - 21
  - 26
  - 31
  macd_signal:
  - 7
  - 9
  - 11
  take_profit_pips:
  - 15
  - 20
  - 30
  - 40
  - 50
  stop_loss_pips:
  - 10
  - 15
  - 20
  - 25
  - 30
parameters_bayesian:
  macd_fast:
  - 8
  - 16
  macd_slow:
  - 21
  - 31
  macd_signal:
  - 7
  - 11
  take_profit_pips:
  - 15
  - 50
  stop_loss_pips:
  - 10
  - 30
