strategy:
  class: NR7Breakout
  module: functions.strategies.nr7_breakout
  results_dir: nr7_breakout
name: NR7 Breakout Strategy
parameters:
  lookback:
  - 6
  - 7
  - 8
  - 10
  take_profit_pips:
  - 20
  - 30
  - 40
  - 60
  stop_loss_pips:
  - 15
  - 20
  - 25
  - 30
parameters_bayesian:
  lookback:
  - 5
  - 12
  take_profit_pips:
  - 15
  - 80
  stop_loss_pips:
  - 10
  - 40
