strategy:
  class: PriceChannelReversion
  module: functions.strategies.price_channel_reversion
  results_dir: price_channel_reversion
name: Price Channel Reversion
parameters:
  channel_period:
  - 14
  - 20
  - 30
  fraction:
  - 0.3
  - 0.4
  - 0.5
  take_profit_pips:
  - 15
  - 25
  - 35
  - 50
  stop_loss_pips:
  - 12
  - 18
  - 24
  - 30
parameters_bayesian:
  channel_period:
  - 10
  - 60
  fraction:
  - 0.2
  - 0.7
  take_profit_pips:
  - 10
  - 70
  stop_loss_pips:
  - 8
  - 40
