strategy:
  class: RSIStrategy
  module: functions.strategies.rsi_strategy
  results_dir: rsi_strategy
name: RSI Mean Reversion Strategy
parameters:
  rsi_period:
  - 9
  - 14
  - 21
  - 28
  oversold:
  - 20
  - 25
  - 30
  - 35
  overbought:
  - 65
  - 70
  - 75
  - 80
  take_profit_pips:
  - 15
  - 20
  - 30
  - 40
  - 50
  stop_loss_pips:
  - 10
  - 15
  - 20
  - 25
  - 30
parameters_bayesian:
  rsi_period:
  - 9
  - 28
  oversold:
  - 20
  - 35
  overbought:
  - 65
  - 80
  take_profit_pips:
  - 15
  - 50
  stop_loss_pips:
  - 10
  - 30
