strategy:
  class: StochasticOscillator
  module: functions.strategies.stochastic_oscillator
  results_dir: stochastic_oscillator
name: Stochastic Oscillator Strategy
parameters:
  stoch_k_period:
  - 10
  - 14
  - 18
  - 21
  stoch_d_period:
  - 3
  - 5
  - 7
  oversold:
  - 15
  - 20
  - 25
  overbought:
  - 75
  - 80
  - 85
  take_profit_pips:
  - 15
  - 20
  - 30
  - 40
  - 50
  stop_loss_pips:
  - 10
  - 15
  - 20
  - 25
  - 30
parameters_bayesian:
  stoch_k_period:
  - 8
  - 25
  stoch_d_period:
  - 3
  - 10
  oversold:
  - 10
  - 30
  overbought:
  - 70
  - 90
  take_profit_pips:
  - 15
  - 60
  stop_loss_pips:
  - 10
  - 35
